// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_image_40_png.preview}
  static const String assets_image_40_png = 'assets/image/40.png';

  /// {@macro assets_generator.assets_image_avatar_jpg.preview}
  static const String assets_image_avatar_jpg = 'assets/image/avatar.jpg';

  /// {@macro assets_generator.assets_image_fluttercandies_grey_png.preview}
  static const String assets_image_fluttercandies_grey_png = 'assets/image/flutterCandies_grey.png';

  /// {@macro assets_generator.assets_image_loading_gif.preview}
  static const String assets_image_loading_gif = 'assets/image/loading.gif';

  /// {@macro assets_generator.assets_image_love_png.preview}
  static const String assets_image_love_png = 'assets/image/love.png';
  static const String assets_image_wu_webp = 'assets/image/wu.webp';
}

final List<String> assetsArray = <String>[
  /// {@macro assets_generator.assets_image_40_png.preview}
  Assets.assets_image_40_png,

  /// {@macro assets_generator.assets_image_avatar_jpg.preview}
  Assets.assets_image_avatar_jpg,

  /// {@macro assets_generator.assets_image_fluttercandies_grey_png.preview}
  Assets.assets_image_fluttercandies_grey_png,

  /// {@macro assets_generator.assets_image_loading_gif.preview}
  Assets.assets_image_loading_gif,

  /// {@macro assets_generator.assets_image_love_png.preview}
  Assets.assets_image_love_png,
  Assets.assets_image_wu_webp,
];
