// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.10
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://picswiper',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'RoutePage'
  ///
  /// [name] : 'fluttercandies://picswiper'
  ///
  /// [routeName] : 'RoutePage'
  ///
  /// [constructors] :
  ///
  /// RoutePage : [Key? key]
  ///
  /// [showStatusBar] : false
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String fluttercandiesPicswiper = 'fluttercandies://picswiper';
}
